import "server-only";

import { GoogleGenAI, Type, type Schema } from "@google/genai";
import { z } from "zod";
import { env } from "@/lib/env";

/**
 * Meeting transcript → structured insights.
 *
 * The input here is a raw Granola paste: speaker labels, filler, half-finished
 * sentences, occasionally a whole day of back-to-backs in one blob. We lean on
 * Gemini's structured-output mode rather than prompting for JSON and hoping,
 * so the only parsing failure left to handle is "the model returned nothing".
 *
 * Everything the model gives back is still treated as untrusted: zod checks the
 * shape, and dates are re-validated by hand because a schema can say "string"
 * but not "a date that actually exists".
 */

export interface MeetingInsights {
  summary: string;
  key_points: string[];
  decisions: string[];
  action_items: Array<{ task: string; due_date: string | null; person: string | null }>;
}

/** Free tier, and fast enough to keep a paste-and-wait flow tolerable. */
const MODEL = "gemini-2.5-flash";

/**
 * Roughly 50k tokens of transcript — comfortably inside the model's window
 * while leaving room for the schema and the response.
 */
const MAX_TRANSCRIPT_CHARS = 200_000;

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

const SYSTEM_INSTRUCTION = `You are the note-taking engine behind a single person's private CRM. \
They paste raw meeting transcripts — usually auto-generated by Granola, so expect speaker labels, \
crosstalk, filler words, mis-transcribed names and abrupt endings — and rely on you to turn each one \
into something they can act on a week later without re-reading it.

Write for that reader: the person who was in the room. They do not need to be told what a meeting is, \
who they are, or that a conversation took place.

summary: two to four sentences of plain prose covering what the meeting was actually about and where \
it landed. Lead with the substance, not the ceremony. No preamble like "In this meeting" or "The team \
discussed".

key_points: the things worth remembering — context, numbers, constraints, concerns raised, useful \
background about the other people. Each one a self-contained sentence that still makes sense with no \
surrounding text. Skip pleasantries and scheduling chatter. Prefer five sharp points over fifteen limp \
ones; an unremarkable meeting is allowed to have two.

decisions: only things that were actually settled — a choice made, a direction agreed, an option ruled \
out. If the conversation ended undecided, that belongs in key_points, not here. An empty list is the \
correct answer far more often than not.

action_items: concrete commitments someone made. Each task must be specific enough to act on without \
the transcript: "Send Priya the revised pricing sheet", not "Follow up". Attribute the owner in \
"person" whenever the transcript makes it clear who took it on — use the name as spoken; use null when \
ownership is genuinely ambiguous, and never guess. Set "due_date" only when a deadline was stated or \
clearly implied; resolve relative language ("next Friday", "end of the month", "in two weeks") against \
the meeting date you are given, and otherwise use null. Do not invent follow-ups to pad the list, do \
not turn a vague "we should think about X" into a task, and do not restate a decision as an action. If \
nobody committed to anything, return an empty array.

Never fabricate. If the transcript is too garbled or too thin to support a field, say less rather than \
inventing more.`;

/**
 * Mirrors MeetingInsights. Descriptions live here rather than in the prompt
 * because the API applies them at decode time, where they bind hardest.
 */
const RESPONSE_SCHEMA: Schema = {
  type: Type.OBJECT,
  properties: {
    summary: {
      type: Type.STRING,
      description: "Two to four sentences of plain prose on what the meeting covered and concluded.",
    },
    key_points: {
      type: Type.ARRAY,
      description: "Self-contained sentences worth remembering later. Empty if the meeting was trivial.",
      items: { type: Type.STRING },
    },
    decisions: {
      type: Type.ARRAY,
      description: "Only matters that were actually settled. Empty if nothing was decided.",
      items: { type: Type.STRING },
    },
    action_items: {
      type: Type.ARRAY,
      description: "Concrete commitments made during the meeting. Empty if nobody committed to anything.",
      items: {
        type: Type.OBJECT,
        properties: {
          task: {
            type: Type.STRING,
            description: "A specific, actionable instruction that stands on its own without the transcript.",
          },
          person: {
            type: Type.STRING,
            description: "Who owns it, named as spoken in the transcript. Null when ownership is unclear.",
            nullable: true,
          },
          due_date: {
            type: Type.STRING,
            description:
              "Deadline as YYYY-MM-DD, resolved against the meeting date. Null unless a date was stated or clearly implied.",
            nullable: true,
          },
        },
        required: ["task", "person", "due_date"],
        propertyOrdering: ["task", "person", "due_date"],
      },
    },
  },
  required: ["summary", "key_points", "decisions", "action_items"],
  propertyOrdering: ["summary", "key_points", "decisions", "action_items"],
};

/**
 * Deliberately looser than MeetingInsights: structured output guarantees the
 * shape, but the model still occasionally omits a nullable field entirely
 * rather than sending null. Normalisation happens after the parse.
 */
const modelResponseSchema = z.object({
  summary: z.string(),
  key_points: z.array(z.string()).nullish(),
  decisions: z.array(z.string()).nullish(),
  action_items: z
    .array(
      z.object({
        task: z.string(),
        person: z.string().nullish(),
        due_date: z.string().nullish(),
      }),
    )
    .nullish(),
});

let client: GoogleGenAI | undefined;

function getClient(): GoogleGenAI {
  if (!env.geminiApiKey) throw new Error("GEMINI_NOT_CONFIGURED");
  client ??= new GoogleGenAI({ apiKey: env.geminiApiKey });
  return client;
}

/**
 * Keep the head and the tail: openings carry the agenda, endings carry the
 * commitments, and the middle is where the rambling lives.
 */
function clampTranscript(transcript: string): string {
  if (transcript.length <= MAX_TRANSCRIPT_CHARS) return transcript;

  const head = Math.floor(MAX_TRANSCRIPT_CHARS * 0.6);
  const tail = MAX_TRANSCRIPT_CHARS - head;
  const elided = transcript.length - MAX_TRANSCRIPT_CHARS;

  return (
    transcript.slice(0, head) +
    `\n\n[... ${elided.toLocaleString("en-US")} characters from the middle of this transcript were ` +
    `omitted to fit the context window. The beginning and end are intact. ...]\n\n` +
    transcript.slice(-tail)
  );
}

/** The anchor the model resolves "next Friday" against. */
function resolveReferenceDate(meetingDate?: string | null): string {
  const candidate = meetingDate?.slice(0, 10);
  if (candidate && isRealDate(candidate)) return candidate;
  return new Date().toISOString().slice(0, 10);
}

/**
 * Regex alone would accept 2026-02-31; the round-trip catches dates that the
 * model composed rather than computed.
 */
function isRealDate(value: string): boolean {
  if (!ISO_DATE.test(value)) return false;
  const parsed = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value;
}

function normalizeDueDate(value: string | null | undefined): string | null {
  if (!value) return null;
  const trimmed = value.trim().slice(0, 10);
  return isRealDate(trimmed) ? trimmed : null;
}

function normalizeText(value: string | null | undefined): string | null {
  const trimmed = value?.trim();
  // Models sometimes render an absent value as the literal word.
  if (!trimmed || /^(null|none|n\/a|unknown|unassigned)$/i.test(trimmed)) return null;
  return trimmed;
}

export async function extractMeetingInsights(input: {
  transcript: string;
  title?: string | null;
  meetingDate?: string | null;
}): Promise<MeetingInsights> {
  const ai = getClient();
  const referenceDate = resolveReferenceDate(input.meetingDate);

  const prompt = [
    `Meeting title: ${input.title?.trim() || "(untitled)"}`,
    `Meeting date: ${referenceDate} (resolve every relative deadline against this date)`,
    "",
    "Transcript:",
    clampTranscript(input.transcript),
  ].join("\n");

  const response = await ai.models.generateContent({
    model: MODEL,
    contents: prompt,
    config: {
      systemInstruction: SYSTEM_INSTRUCTION,
      responseMimeType: "application/json",
      responseSchema: RESPONSE_SCHEMA,
      // Extraction is a reading task, not a creative one.
      temperature: 0.2,
      // Thinking buys little on straight extraction and can push a long
      // transcript past the route's 60s budget.
      thinkingConfig: { thinkingBudget: 0 },
    },
  });

  const text = response.text;
  if (!text) {
    // Almost always a safety block or an empty candidate rather than a network
    // problem — the SDK would have thrown for those.
    const reason = response.candidates?.[0]?.finishReason;
    throw new Error(
      `Gemini returned no content${reason ? ` (finishReason: ${reason})` : ""}.`,
    );
  }

  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    throw new Error("Gemini returned malformed JSON despite structured output.");
  }

  const parsed = modelResponseSchema.safeParse(raw);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((issue) => `${issue.path.join(".") || "(root)"}: ${issue.message}`)
      .join("; ");
    throw new Error(`Gemini returned an unexpected shape — ${issues}`);
  }

  const data = parsed.data;

  return {
    summary: data.summary.trim(),
    key_points: (data.key_points ?? []).map((point) => point.trim()).filter(Boolean),
    decisions: (data.decisions ?? []).map((decision) => decision.trim()).filter(Boolean),
    action_items: (data.action_items ?? [])
      .map((item) => ({
        task: item.task.trim(),
        due_date: normalizeDueDate(item.due_date),
        person: normalizeText(item.person),
      }))
      // A task with no text is unusable, and the DB rejects it anyway.
      .filter((item) => item.task.length > 0),
  };
}
